name: Test

on:
  push:
    branches: [ main ]  # veya istediğiniz branch adı
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Eğer varsa

    - name: Run tests
      run: python -m unittest discover -s tests